-- 6DNX real PIX commerce foundation.
-- IMPORTANT: review in an isolated Supabase branch before applying.
-- Existing catalog prices are imported as DRAFT and cannot create charges.

create extension if not exists pgcrypto;

create table if not exists public.commerce_offers (
  id uuid primary key default gen_random_uuid(),
  product_source_key text not null
    references public.product_catalog(source_key) on delete restrict,
  variant_name text not null check (char_length(variant_name) between 1 and 120),
  amount_cents integer not null check (amount_cents between 1 and 10000000),
  currency text not null default 'BRL' check (currency = 'BRL'),
  status text not null default 'draft'
    check (status in ('draft', 'approved', 'suspended')),
  approval_note text check (char_length(approval_note) <= 240),
  approved_at timestamptz,
  approved_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (product_source_key, variant_name),
  check (
    status <> 'approved'
    or (approved_at is not null and approval_note is not null)
  )
);

create index if not exists commerce_offers_status_idx
  on public.commerce_offers (status, product_source_key);

create table if not exists public.commerce_orders (
  id uuid primary key,
  client_request_id uuid not null unique,
  external_id text not null unique
    check (char_length(external_id) between 1 and 100),
  offer_id uuid not null
    references public.commerce_offers(id) on delete restrict,
  product_source_key text not null,
  product_slug text not null check (char_length(product_slug) between 1 and 96),
  product_title text not null check (char_length(product_title) between 1 and 100),
  variant_name text not null check (char_length(variant_name) between 1 and 120),
  amount_cents integer not null check (amount_cents between 1 and 10000000),
  currency text not null default 'BRL' check (currency = 'BRL'),
  payer_name text not null check (char_length(payer_name) between 3 and 100),
  payer_document_hash text not null
    check (payer_document_hash ~ '^[a-f0-9]{64}$'),
  payer_document_last4 text not null
    check (payer_document_last4 ~ '^[0-9]{4}$'),
  request_fingerprint_hash text not null
    check (request_fingerprint_hash ~ '^[a-f0-9]{64}$'),
  status text not null default 'pending_payment'
    check (
      status in (
        'pending_payment',
        'payment_creation_failed',
        'paid',
        'failed',
        'cancelled'
      )
    ),
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists commerce_orders_fingerprint_created_idx
  on public.commerce_orders (request_fingerprint_hash, created_at desc);
create index if not exists commerce_orders_status_created_idx
  on public.commerce_orders (status, created_at desc);

create table if not exists public.commerce_payment_attempts (
  order_id uuid primary key
    references public.commerce_orders(id) on delete cascade,
  provider text not null default 'storm_wallet'
    check (provider = 'storm_wallet'),
  provider_payment_id text check (
    provider_payment_id is null
    or char_length(provider_payment_id) between 1 and 160
  ),
  idempotency_key text check (
    idempotency_key is null
    or char_length(idempotency_key) between 1 and 100
  ),
  provider_status text check (
    provider_status is null
    or provider_status in ('PENDENTE', 'COMPLETO', 'FALHA')
  ),
  provider_complete_observed_at timestamptz,
  last_polled_at timestamptz,
  last_error_code text check (
    last_error_code is null or char_length(last_error_code) <= 80
  ),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists commerce_attempts_provider_payment_unique
  on public.commerce_payment_attempts (provider_payment_id)
  where provider_payment_id is not null;
create unique index if not exists commerce_attempts_idempotency_unique
  on public.commerce_payment_attempts (idempotency_key)
  where idempotency_key is not null;

create table if not exists public.commerce_webhook_events (
  id bigint generated by default as identity primary key,
  event_key text not null unique check (event_key ~ '^[a-f0-9]{64}$'),
  order_id uuid not null
    references public.commerce_orders(id) on delete cascade,
  event_name text not null
    check (event_name in ('payment.completed', 'payment.failed')),
  provider_payment_id text not null
    check (char_length(provider_payment_id) between 1 and 160),
  external_id text not null check (char_length(external_id) between 1 and 100),
  amount_cents integer not null check (amount_cents between 1 and 10000000),
  provider_status text not null check (provider_status in ('COMPLETO', 'FALHA')),
  processed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (provider_payment_id, event_name)
);

create index if not exists commerce_webhook_events_order_idx
  on public.commerce_webhook_events (order_id, created_at desc);

create or replace function public.touch_commerce_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := clock_timestamp();
  return new;
end;
$$;

revoke all on function public.touch_commerce_updated_at()
  from public, anon, authenticated;

drop trigger if exists commerce_offers_touch_updated_at
  on public.commerce_offers;
create trigger commerce_offers_touch_updated_at
before update on public.commerce_offers
for each row execute function public.touch_commerce_updated_at();

drop trigger if exists commerce_orders_touch_updated_at
  on public.commerce_orders;
create trigger commerce_orders_touch_updated_at
before update on public.commerce_orders
for each row execute function public.touch_commerce_updated_at();

drop trigger if exists commerce_attempts_touch_updated_at
  on public.commerce_payment_attempts;
create trigger commerce_attempts_touch_updated_at
before update on public.commerce_payment_attempts
for each row execute function public.touch_commerce_updated_at();

alter table public.commerce_offers enable row level security;
alter table public.commerce_orders enable row level security;
alter table public.commerce_payment_attempts enable row level security;
alter table public.commerce_webhook_events enable row level security;

revoke all on table public.commerce_offers from anon, authenticated;
revoke all on table public.commerce_orders from anon, authenticated;
revoke all on table public.commerce_payment_attempts from anon, authenticated;
revoke all on table public.commerce_webhook_events from anon, authenticated;
grant select, insert, update on table public.commerce_offers to authenticated;
grant select on table public.commerce_orders to authenticated;
grant select on table public.commerce_payment_attempts to authenticated;
grant select on table public.commerce_webhook_events to authenticated;

-- Supabase projects created after the Data API privilege hardening no longer
-- grant public-schema table access implicitly. Keep the server role narrowly
-- scoped to the operations used by CommerceRepository.
revoke all on table public.commerce_offers from service_role;
revoke all on table public.commerce_orders from service_role;
revoke all on table public.commerce_payment_attempts from service_role;
revoke all on table public.commerce_webhook_events from service_role;
grant select on table public.commerce_offers to service_role;
grant select, insert, update on table public.commerce_orders to service_role;
grant select, insert, update on table public.commerce_payment_attempts to service_role;
grant select on table public.commerce_webhook_events to service_role;

drop policy if exists "Admins manage commerce offers"
  on public.commerce_offers;
create policy "Admins manage commerce offers"
on public.commerce_offers
for all
to authenticated
using (public.is_catalog_admin())
with check (public.is_catalog_admin());

drop policy if exists "Admins read commerce orders"
  on public.commerce_orders;
create policy "Admins read commerce orders"
on public.commerce_orders
for select
to authenticated
using (public.is_catalog_admin());

drop policy if exists "Admins read commerce attempts"
  on public.commerce_payment_attempts;
create policy "Admins read commerce attempts"
on public.commerce_payment_attempts
for select
to authenticated
using (public.is_catalog_admin());

drop policy if exists "Admins read commerce webhook events"
  on public.commerce_webhook_events;
create policy "Admins read commerce webhook events"
on public.commerce_webhook_events
for select
to authenticated
using (public.is_catalog_admin());

-- The signed webhook is the only path that can mark an order paid. It locks
-- the order, validates provider identity and amount, records the event once,
-- then changes state inside one transaction.
create or replace function public.process_storm_payment_event(
  p_event_key text,
  p_event_name text,
  p_provider_payment_id text,
  p_external_id text,
  p_amount_cents integer,
  p_provider_status text,
  p_completed_at timestamptz default null
)
returns table (
  order_id uuid,
  product_slug text,
  product_title text,
  variant_name text,
  amount_cents integer,
  order_status text,
  event_inserted boolean
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_order_id uuid;
  v_order public.commerce_orders%rowtype;
  v_attempt public.commerce_payment_attempts%rowtype;
  v_inserted boolean := false;
  v_row_count integer := 0;
begin
  if p_event_name not in ('payment.completed', 'payment.failed')
    or p_provider_status not in ('COMPLETO', 'FALHA')
    or (p_event_name = 'payment.completed' and p_provider_status <> 'COMPLETO')
    or (p_event_name = 'payment.failed' and p_provider_status <> 'FALHA') then
    raise exception using errcode = '22023', message = 'invalid storm event';
  end if;

  select o.* into v_order
  from public.commerce_orders as o
  where o.external_id = p_external_id
  for update;
  if not found then
    raise exception using errcode = 'P0002', message = 'order not found';
  end if;
  v_order_id := v_order.id;
  if v_order.amount_cents <> p_amount_cents then
    raise exception using errcode = '22023', message = 'amount mismatch';
  end if;

  select a.* into v_attempt
  from public.commerce_payment_attempts as a
  where a.order_id = v_order.id
  for update;
  if found
    and v_attempt.provider_payment_id is not null
    and v_attempt.provider_payment_id <> p_provider_payment_id then
    raise exception using errcode = '22023', message = 'provider id mismatch';
  end if;

  insert into public.commerce_webhook_events (
    event_key,
    order_id,
    event_name,
    provider_payment_id,
    external_id,
    amount_cents,
    provider_status
  )
  values (
    p_event_key,
    v_order.id,
    p_event_name,
    p_provider_payment_id,
    p_external_id,
    p_amount_cents,
    p_provider_status
  )
  on conflict do nothing;
  get diagnostics v_row_count = row_count;
  v_inserted := v_row_count > 0;

  if v_inserted then
    insert into public.commerce_payment_attempts (
      order_id,
      provider,
      provider_payment_id,
      idempotency_key,
      provider_status,
      provider_complete_observed_at,
      updated_at
    )
    values (
      v_order.id,
      'storm_wallet',
      p_provider_payment_id,
      v_order.external_id,
      p_provider_status,
      case when p_provider_status = 'COMPLETO' then clock_timestamp() end,
      clock_timestamp()
    )
    on conflict (order_id) do update
    set
      provider_payment_id = excluded.provider_payment_id,
      idempotency_key = excluded.idempotency_key,
      provider_status = case
        when public.commerce_payment_attempts.provider_status = 'COMPLETO'
          then public.commerce_payment_attempts.provider_status
        else excluded.provider_status
      end,
      provider_complete_observed_at = coalesce(
        public.commerce_payment_attempts.provider_complete_observed_at,
        excluded.provider_complete_observed_at
      ),
      updated_at = clock_timestamp();

    if p_provider_status = 'COMPLETO' then
      update public.commerce_orders as o
      set
        status = 'paid',
        paid_at = coalesce(o.paid_at, p_completed_at, clock_timestamp()),
        updated_at = clock_timestamp()
      where o.id = v_order.id
        and o.status in ('pending_payment', 'payment_creation_failed', 'failed');
    elsif p_provider_status = 'FALHA' then
      update public.commerce_orders as o
      set status = 'failed', updated_at = clock_timestamp()
      where o.id = v_order.id and o.status <> 'paid';
    end if;
  end if;

  select o.* into v_order
  from public.commerce_orders as o
  where o.id = v_order_id;

  return query select
    v_order.id,
    v_order.product_slug,
    v_order.product_title,
    v_order.variant_name,
    v_order.amount_cents,
    v_order.status,
    v_inserted;
end;
$$;

revoke all on function public.process_storm_payment_event(
  text, text, text, text, integer, text, timestamptz
) from public, anon, authenticated;
grant execute on function public.process_storm_payment_event(
  text, text, text, text, integer, text, timestamptz
) to service_role;

-- Copy the current catalog into the commercial review queue. Nothing below is
-- approved automatically, even when a reference price exists in the catalog.
insert into public.commerce_offers (
  product_source_key,
  variant_name,
  amount_cents,
  status
)
select
  catalog.source_key,
  variant.value ->> 'name',
  round(((variant.value ->> 'priceBRL')::numeric) * 100)::integer,
  'draft'
from public.product_catalog as catalog
cross join lateral jsonb_array_elements(catalog.variants) as variant(value)
where
  nullif(variant.value ->> 'name', '') is not null
  and (variant.value ->> 'priceBRL') ~ '^[0-9]+([.][0-9]{1,2})?$'
  and ((variant.value ->> 'priceBRL')::numeric) > 0
on conflict (product_source_key, variant_name) do nothing;
