-- 6DNX product CMS.
-- Review this migration in an isolated Supabase branch before applying it.

create extension if not exists pgcrypto;

create table if not exists public.product_catalog (
  id uuid primary key default gen_random_uuid(),
  source_key text not null unique
    check (char_length(source_key) between 1 and 140),
  slug text not null unique
    check (
      char_length(slug) between 1 and 96
      and slug ~ '^[A-Za-z0-9]+(-[A-Za-z0-9]+)*$'
    ),
  title text not null check (char_length(title) between 1 and 100),
  category text not null check (char_length(category) between 1 and 80),
  tagline text not null check (char_length(tagline) between 1 and 160),
  description text not null default ''
    check (char_length(description) <= 4000),
  features jsonb not null default '[]'::jsonb
    check (jsonb_typeof(features) = 'array'),
  system_support jsonb not null default '[]'::jsonb
    check (jsonb_typeof(system_support) = 'array'),
  menu_keys jsonb not null default '[]'::jsonb
    check (jsonb_typeof(menu_keys) = 'array'),
  tutorial_steps jsonb not null default '[]'::jsonb
    check (jsonb_typeof(tutorial_steps) = 'array'),
  image text not null check (char_length(image) between 1 and 500),
  status text not null default 'available'
    check (status in ('available', 'custom')),
  variants jsonb not null default '[]'::jsonb
    check (jsonb_typeof(variants) = 'array'),
  youtube_id text
    check (youtube_id is null or youtube_id ~ '^[A-Za-z0-9_-]{11}$'),
  video_orientation text not null default 'landscape'
    check (video_orientation in ('landscape', 'portrait')),
  theme jsonb not null
    default '{"accentColor":"#e3062c","textColor":"#f7f3f4","surfaceColor":"#0b0708"}'::jsonb
    check (jsonb_typeof(theme) = 'object'),
  publication_state text not null default 'draft'
    check (publication_state in ('draft', 'published', 'archived')),
  catalog_order integer not null default 0
    check (catalog_order between 0 and 9999),
  revision integer not null default 1 check (revision >= 1),
  last_change_note text check (char_length(last_change_note) <= 240),
  updated_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.product_catalog
  drop constraint if exists product_catalog_pinned_items_stay_published;
alter table public.product_catalog
  add constraint product_catalog_pinned_items_stay_published
  check (
    source_key not in (
      'dayz-private',
      'cs-2',
      'arena-breakout',
      'escape-from-tarkov-6DNX-software',
      'rust-6DNX-software',
      'pubg-6DNX-software'
    )
    or publication_state = 'published'
  );

create index if not exists product_catalog_publication_order_idx
  on public.product_catalog (publication_state, catalog_order, created_at);

create table if not exists public.product_catalog_revisions (
  id bigint generated by default as identity primary key,
  product_id uuid not null
    references public.product_catalog(id) on delete cascade,
  revision integer not null check (revision >= 1),
  snapshot jsonb not null check (jsonb_typeof(snapshot) = 'object'),
  change_note text check (char_length(change_note) <= 240),
  changed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (product_id, revision)
);

create index if not exists product_catalog_revisions_product_idx
  on public.product_catalog_revisions (product_id, revision desc);

create or replace function public.is_catalog_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin',
    false
  );
$$;

revoke all on function public.is_catalog_admin() from public;
grant execute on function public.is_catalog_admin() to anon, authenticated;

create or replace function public.capture_product_catalog_revision()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.source_key is distinct from old.source_key then
    raise exception 'source_key is immutable';
  end if;

  insert into public.product_catalog_revisions (
    product_id,
    revision,
    snapshot,
    change_note,
    changed_by
  )
  values (
    old.id,
    old.revision,
    to_jsonb(old),
    nullif(btrim(new.last_change_note), ''),
    auth.uid()
  );

  new.revision := old.revision + 1;
  new.updated_at := clock_timestamp();
  new.updated_by := auth.uid();
  return new;
end;
$$;

drop trigger if exists product_catalog_capture_revision
  on public.product_catalog;
create trigger product_catalog_capture_revision
before update on public.product_catalog
for each row
when (old.* is distinct from new.*)
execute function public.capture_product_catalog_revision();

alter table public.product_catalog enable row level security;
alter table public.product_catalog_revisions enable row level security;

revoke all on table public.product_catalog from anon, authenticated;
grant select on table public.product_catalog to anon, authenticated;
grant insert, update on table public.product_catalog to authenticated;
revoke all on table public.product_catalog_revisions from anon, authenticated;
grant select on table public.product_catalog_revisions to authenticated;

drop policy if exists "Published catalog is publicly readable"
  on public.product_catalog;
create policy "Published catalog is publicly readable"
on public.product_catalog
for select
to anon, authenticated
using (
  publication_state = 'published'
  or public.is_catalog_admin()
);

drop policy if exists "Admins can insert catalog products"
  on public.product_catalog;
create policy "Admins can insert catalog products"
on public.product_catalog
for insert
to authenticated
with check (public.is_catalog_admin());

drop policy if exists "Admins can update catalog products"
  on public.product_catalog;
create policy "Admins can update catalog products"
on public.product_catalog
for update
to authenticated
using (public.is_catalog_admin())
with check (public.is_catalog_admin());

drop policy if exists "Admins can read catalog history"
  on public.product_catalog_revisions;
create policy "Admins can read catalog history"
on public.product_catalog_revisions
for select
to authenticated
using (public.is_catalog_admin());

-- No DELETE policy by design. Products are archived so an operator can recover
-- them without database intervention.

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'product-assets',
  'product-assets',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public product assets are readable"
  on storage.objects;
create policy "Public product assets are readable"
on storage.objects
for select
to public
using (bucket_id = 'product-assets');

drop policy if exists "Admins can upload product assets"
  on storage.objects;
create policy "Admins can upload product assets"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'product-assets'
  and public.is_catalog_admin()
);

drop policy if exists "Admins can update product assets"
  on storage.objects;
create policy "Admins can update product assets"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'product-assets'
  and public.is_catalog_admin()
)
with check (
  bucket_id = 'product-assets'
  and public.is_catalog_admin()
);

drop policy if exists "Admins can remove product assets"
  on storage.objects;
create policy "Admins can remove product assets"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'product-assets'
  and public.is_catalog_admin()
);
