-- Server-side StorM reconciliation for already-created PIX payments.
--
-- This migration does not create charges and does not change checkout flags.
-- It adds a second, auditable proof source: an authenticated GET to the
-- provider status endpoint, matched against the stored provider id, external
-- id and amount. All state transitions remain atomic and idempotent.

create table if not exists public.commerce_reconciliation_events (
  id bigint generated by default as identity primary key,
  reconciliation_key text not null unique
    check (reconciliation_key ~ '^[a-f0-9]{64}$'),
  order_id uuid not null
    references public.commerce_orders(id) on delete cascade,
  provider_payment_id text not null
    check (char_length(provider_payment_id) between 1 and 160),
  external_id text not null check (char_length(external_id) between 1 and 100),
  amount_cents integer not null check (amount_cents between 1 and 10000000),
  provider_status text not null check (provider_status in ('COMPLETO', 'FALHA')),
  observed_at timestamptz not null,
  processed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (provider_payment_id, provider_status)
);

create index if not exists commerce_reconciliation_events_order_idx
  on public.commerce_reconciliation_events (order_id, created_at desc);

alter table public.commerce_reconciliation_events enable row level security;

revoke all on table public.commerce_reconciliation_events
  from public, anon, authenticated, service_role;
grant select on table public.commerce_reconciliation_events to authenticated;
grant select on table public.commerce_reconciliation_events to service_role;

drop policy if exists "Admins read commerce reconciliation events"
  on public.commerce_reconciliation_events;
create policy "Admins read commerce reconciliation events"
on public.commerce_reconciliation_events
for select
to authenticated
using (public.is_catalog_admin());

-- The service role receives only a bounded list of known payment attempts.
-- Final-state rows disappear from this queue, so a failed payment is not
-- queried forever. Checkout status polling remains the immediate path.
create or replace function public.list_storm_reconciliation_candidates(
  p_limit integer default 10
)
returns table (
  order_id uuid,
  external_id text,
  amount_cents integer,
  product_slug text,
  product_title text,
  variant_name text,
  provider_payment_id text
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    o.id,
    o.external_id,
    o.amount_cents,
    o.product_slug,
    o.product_title,
    o.variant_name,
    a.provider_payment_id
  from public.commerce_orders as o
  inner join public.commerce_payment_attempts as a
    on a.order_id = o.id
  where o.status in ('pending_payment', 'payment_creation_failed')
    and a.provider = 'storm_wallet'
    and a.provider_payment_id is not null
    and o.created_at >= now() - interval '30 days'
    and (
      a.last_polled_at is null
      or a.last_polled_at <= now() - interval '1 minute'
    )
  order by o.created_at asc, o.id asc
  limit least(greatest(coalesce(p_limit, 10), 1), 20);
$$;

revoke all on function public.list_storm_reconciliation_candidates(integer)
  from public, anon, authenticated, service_role;
grant execute on function public.list_storm_reconciliation_candidates(integer)
  to service_role;

-- Settle one existing payment from authenticated provider API evidence.
-- The function locks order then attempt (the same order as the webhook),
-- validates all immutable identifiers, records evidence once and transitions
-- state within one transaction.
create or replace function public.reconcile_storm_payment(
  p_reconciliation_key text,
  p_provider_payment_id text,
  p_external_id text,
  p_amount_cents integer,
  p_provider_status text,
  p_observed_at timestamptz
)
returns table (
  order_id uuid,
  product_slug text,
  product_title text,
  variant_name text,
  amount_cents integer,
  order_status text,
  reconciliation_inserted boolean,
  payment_transitioned boolean
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_order_id uuid;
  v_order public.commerce_orders%rowtype;
  v_attempt public.commerce_payment_attempts%rowtype;
  v_inserted boolean := false;
  v_was_paid boolean := false;
  v_transitioned boolean := false;
  v_row_count integer := 0;
begin
  if p_reconciliation_key is null
    or p_reconciliation_key !~ '^[a-f0-9]{64}$'
    or p_provider_payment_id is null
    or char_length(p_provider_payment_id) not between 1 and 160
    or p_external_id is null
    or char_length(p_external_id) not between 1 and 100
    or p_provider_status not in ('COMPLETO', 'FALHA')
    or p_amount_cents is null
    or p_amount_cents not between 1 and 10000000
    or p_observed_at is null
    or p_observed_at > clock_timestamp() + interval '5 minutes' then
    raise exception using errcode = '22023', message = 'invalid reconciliation evidence';
  end if;

  select o.* into v_order
  from public.commerce_orders as o
  where o.external_id = p_external_id
  for update;
  if not found then
    raise exception using errcode = 'P0002', message = 'order not found';
  end if;
  v_order_id := v_order.id;
  v_was_paid := v_order.status = 'paid';

  if v_order.amount_cents <> p_amount_cents then
    raise exception using errcode = '22023', message = 'amount mismatch';
  end if;

  select a.* into v_attempt
  from public.commerce_payment_attempts as a
  where a.order_id = v_order.id
  for update;
  if not found
    or v_attempt.provider_payment_id is null
    or v_attempt.provider_payment_id <> p_provider_payment_id
    or v_attempt.idempotency_key is distinct from v_order.external_id then
    raise exception using errcode = '22023', message = 'payment attempt mismatch';
  end if;

  insert into public.commerce_reconciliation_events (
    reconciliation_key,
    order_id,
    provider_payment_id,
    external_id,
    amount_cents,
    provider_status,
    observed_at
  )
  values (
    p_reconciliation_key,
    v_order.id,
    p_provider_payment_id,
    p_external_id,
    p_amount_cents,
    p_provider_status,
    p_observed_at
  )
  on conflict do nothing;
  get diagnostics v_row_count = row_count;
  v_inserted := v_row_count > 0;

  if v_inserted then
    update public.commerce_payment_attempts as a
    set
      provider_status = case
        when a.provider_status = 'COMPLETO' then a.provider_status
        else p_provider_status
      end,
      provider_complete_observed_at = case
        when p_provider_status = 'COMPLETO'
          then coalesce(a.provider_complete_observed_at, p_observed_at)
        else a.provider_complete_observed_at
      end,
      last_polled_at = p_observed_at,
      last_error_code = null,
      updated_at = clock_timestamp()
    where a.order_id = v_order.id;

    if p_provider_status = 'COMPLETO' then
      update public.commerce_orders as o
      set
        status = 'paid',
        paid_at = coalesce(o.paid_at, p_observed_at),
        updated_at = clock_timestamp()
      where o.id = v_order.id
        and o.status in ('pending_payment', 'payment_creation_failed', 'failed');
    else
      update public.commerce_orders as o
      set status = 'failed', updated_at = clock_timestamp()
      where o.id = v_order.id and o.status <> 'paid';
    end if;
  end if;

  select o.* into v_order
  from public.commerce_orders as o
  where o.id = v_order_id;
  v_transitioned := not v_was_paid and v_order.status = 'paid';

  return query select
    v_order.id,
    v_order.product_slug,
    v_order.product_title,
    v_order.variant_name,
    v_order.amount_cents,
    v_order.status,
    v_inserted,
    v_transitioned;
end;
$$;

revoke all on function public.reconcile_storm_payment(
  text, text, text, integer, text, timestamptz
) from public, anon, authenticated, service_role;
grant execute on function public.reconcile_storm_payment(
  text, text, text, integer, text, timestamptz
) to service_role;

-- Versioned webhook RPC. It keeps the signed webhook path authoritative while
-- exposing whether this exact transaction performed the paid transition. That
-- prevents duplicate Discord notifications when webhook and reconciliation
-- race. The previous RPC remains available to the currently deployed code.
create or replace function public.process_storm_payment_event_v2(
  p_event_key text,
  p_event_name text,
  p_provider_payment_id text,
  p_external_id text,
  p_amount_cents integer,
  p_provider_status text,
  p_completed_at timestamptz default null
)
returns table (
  order_id uuid,
  product_slug text,
  product_title text,
  variant_name text,
  amount_cents integer,
  order_status text,
  event_inserted boolean,
  payment_transitioned boolean
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_order_id uuid;
  v_order public.commerce_orders%rowtype;
  v_attempt public.commerce_payment_attempts%rowtype;
  v_inserted boolean := false;
  v_was_paid boolean := false;
  v_transitioned boolean := false;
  v_row_count integer := 0;
begin
  if p_event_name not in ('payment.completed', 'payment.failed')
    or p_provider_status not in ('COMPLETO', 'FALHA')
    or (p_event_name = 'payment.completed' and p_provider_status <> 'COMPLETO')
    or (p_event_name = 'payment.failed' and p_provider_status <> 'FALHA') then
    raise exception using errcode = '22023', message = 'invalid storm event';
  end if;

  select o.* into v_order
  from public.commerce_orders as o
  where o.external_id = p_external_id
  for update;
  if not found then
    raise exception using errcode = 'P0002', message = 'order not found';
  end if;
  v_order_id := v_order.id;
  v_was_paid := v_order.status = 'paid';

  if v_order.amount_cents <> p_amount_cents then
    raise exception using errcode = '22023', message = 'amount mismatch';
  end if;

  select a.* into v_attempt
  from public.commerce_payment_attempts as a
  where a.order_id = v_order.id
  for update;
  if found
    and v_attempt.provider_payment_id is not null
    and v_attempt.provider_payment_id <> p_provider_payment_id then
    raise exception using errcode = '22023', message = 'provider id mismatch';
  end if;

  insert into public.commerce_webhook_events (
    event_key,
    order_id,
    event_name,
    provider_payment_id,
    external_id,
    amount_cents,
    provider_status
  )
  values (
    p_event_key,
    v_order.id,
    p_event_name,
    p_provider_payment_id,
    p_external_id,
    p_amount_cents,
    p_provider_status
  )
  on conflict do nothing;
  get diagnostics v_row_count = row_count;
  v_inserted := v_row_count > 0;

  if v_inserted then
    insert into public.commerce_payment_attempts (
      order_id,
      provider,
      provider_payment_id,
      idempotency_key,
      provider_status,
      provider_complete_observed_at,
      updated_at
    )
    values (
      v_order.id,
      'storm_wallet',
      p_provider_payment_id,
      v_order.external_id,
      p_provider_status,
      case when p_provider_status = 'COMPLETO' then clock_timestamp() end,
      clock_timestamp()
    )
    on conflict on constraint commerce_payment_attempts_pkey do update
    set
      provider_payment_id = excluded.provider_payment_id,
      idempotency_key = excluded.idempotency_key,
      provider_status = case
        when public.commerce_payment_attempts.provider_status = 'COMPLETO'
          then public.commerce_payment_attempts.provider_status
        else excluded.provider_status
      end,
      provider_complete_observed_at = coalesce(
        public.commerce_payment_attempts.provider_complete_observed_at,
        excluded.provider_complete_observed_at
      ),
      updated_at = clock_timestamp();

    if p_provider_status = 'COMPLETO' then
      update public.commerce_orders as o
      set
        status = 'paid',
        paid_at = coalesce(o.paid_at, p_completed_at, clock_timestamp()),
        updated_at = clock_timestamp()
      where o.id = v_order.id
        and o.status in ('pending_payment', 'payment_creation_failed', 'failed');
    else
      update public.commerce_orders as o
      set status = 'failed', updated_at = clock_timestamp()
      where o.id = v_order.id and o.status <> 'paid';
    end if;
  end if;

  select o.* into v_order
  from public.commerce_orders as o
  where o.id = v_order_id;
  v_transitioned := not v_was_paid and v_order.status = 'paid';

  return query select
    v_order.id,
    v_order.product_slug,
    v_order.product_title,
    v_order.variant_name,
    v_order.amount_cents,
    v_order.status,
    v_inserted,
    v_transitioned;
end;
$$;

revoke all on function public.process_storm_payment_event_v2(
  text, text, text, text, integer, text, timestamptz
) from public, anon, authenticated, service_role;
grant execute on function public.process_storm_payment_event_v2(
  text, text, text, text, integer, text, timestamptz
) to service_role;
